build(lua5/buster/Dockerfile): rewrite, make better use of luarocks
- Install and pre-package the dependencies as "rocks" which are then
used for "networkless" installation at the later ("runtime") stage.
We'll end up with a smaller image.

- Use exclusively Lua 5.3

diff --git a/lua5/docker/buster/Dockerfile b/lua5/docker/buster/Dockerfile
--- a/lua5/docker/buster/Dockerfile
+++ b/lua5/docker/buster/Dockerfile
@@ -3,46 +3,75 @@
 # jomiel-examples
 #
 # Copyright
-#  2019 Toni Gündoğdu
+#  2019-2021 Toni Gündoğdu
 #
 #
 # SPDX-License-Identifier: Apache-2.0
 #
-FROM debian:buster-slim
+
+# stage: build-image
+#
+FROM debian:buster-slim AS build-image
 
 WORKDIR /app
 
-COPY lua5/bin/ ./bin/
-COPY lua5/lib/ ./lib/
-COPY proto/ ./proto/
+ENV ROCKSPEC demo-0.1.0-1.rockspec
+
+COPY lua5/${ROCKSPEC} ./
 
 ENV BUILD_DEPS \
-        build-essential \
-        libzmq3-dev \
-        luarocks \
-        git
+  build-essential \
+  liblua5.3-dev \
+  libyaml-dev \
+  libzmq3-dev \
+  luarocks \
+  lua5.3
 
 RUN set -eux \
-    # Install the build deps.
     ; apt-get -qq update \
     && apt-get -qq --no-install-recommends install $BUILD_DEPS \
-    # Install the lua runtime deps.
-    && eval "set -- lua-protobuf argparse serpent log4l lzmq"; \
-        for dep; do \
-            luarocks --local-tree install $dep || break; \
-        done \
-    # Modify the import path for .proto files.
-    && sed -i 's/\.\.\/proto/\.\/proto/' lib/demo/jomiel.lua \
-    # Cleanup (stage #1).
-    && apt-get -qq purge $BUILD_DEPS \
-    && apt-get -qq autoremove \
-    # Install the required runtime.
-    && apt-get -qq --no-install-recommends install \
-        libzmq5 \
-        lua5.1 \
-    # Cleanup (stage #2).
-    && rm -rf /var/lib/apt/lists/*
+    # Install the Lua deps.
+    && luarocks build --tree ./local --only-deps ${ROCKSPEC} \
+    # Build the .rock from each installed dep.
+    && luarocks list --tree ./local/ --porcelain | awk '{print $1}' \
+        | xargs -I {} bash -c 'luarocks pack --tree ./local {}' \
+    # Move the .rock
+    && mkdir -p rocks/ \
+    && mv *.rock rocks/ \
+    # Generate the manifest files for the .rock
+    && luarocks-admin make-manifest --tree ./local rocks/
 
-ENTRYPOINT ["/app/bin/demo"]
+# stage: runtime-image
+#
+FROM debian:buster-slim AS runtime-image
+
+WORKDIR /app
+
+ENV ROCKSPEC demo-0.1.0-1.rockspec
+
+COPY lua5/${ROCKSPEC} ./
+
+COPY lua5/bin/demo ./bin/demo
+COPY lua5/src/ ./src/
+
+COPY --from=build-image /app/rocks/ /app/rocks/
+COPY proto/ ./proto/
+
+RUN set -eux \
+    ; apt-get -qq update \
+    && apt-get -qq --no-install-recommends install \
+        libyaml-dev \
+        luarocks \
+        libzmq5 \
+        lua5.3 \
+    # Install the local .rocks
+    && luarocks build --tree ./local \
+        --only-server rocks/ --only-deps ${ROCKSPEC} \
+    # Cleanup.
+    && rm -rf /var/lib/apt/lists/* \
+    && apt-get purge luarocks -y \
+    && rm -rf rocks ${ROCKSPEC}
+
+ENTRYPOINT ["/app/bin/demo", "--proto-dir", "./proto"]
 
 CMD ["-h"]
